config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :admin do
    get  '/admins/auth/:provider',          to: 'admins/omniauth_callbacks#passthru', as: :admin_omniauth_authorize
    post '/admins/auth/:provider',          to: 'admins/omniauth_callbacks#passthru'
    get  '/admins/auth/:provider/callback', to: 'admins/omniauth_callbacks#google_oauth2', as: :admin_omniauth_callback
    post '/admins/auth/:provider/callback', to: 'admins/omniauth_callbacks#google_oauth2'
  end

  get 'dashboard', to: 'dashboards#show', as: :dashboard

  resources :user_books
  resources :users
  resources :books
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(
      uid: uid,
      full_name: full_name,
      avatar_url: avatar_url,
      password: Devise.friendly_token[0, 20]
    ).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :user_books
    has_many :users, through: :user_books
  
    validates :title, :author, :price, :published_date, presence: true
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :user_books
    has_many :books, through: :user_books
  end
  
  

app/models/user_book.rb
class UserBook < ApplicationRecord
    belongs_to :user
    belongs_to :book
  end
  

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    Rails.logger.info ">>>> Entered google_oauth2 callback"
    Rails.logger.info ">>>> Raw omniauth.auth = #{request.env["omniauth.auth"].inspect}"

    @admin = Admin.from_google(**from_google_params)

    if @admin.persisted?
      Rails.logger.info ">>>> Successfully authenticated Admin: #{@admin.email}"
      sign_out_all_scopes
      flash[:notice] = "Successfully authenticated from Google account."
      sign_in_and_redirect @admin, event: :authentication
    else
      Rails.logger.warn ">>>> Google authentication failed for: #{from_google_params[:email]}"
      flash[:alert] = "Google authentication failed."
      redirect_to new_admin_session_path
    end
  end

  private

  def from_google_params
    auth = request.env["omniauth.auth"]
    {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed."
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :price, :published_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_admin!

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user_book, only: %i[ show edit update destroy ]

  # GET /user_books or /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1 or /user_books/1.json
  def show
  end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit
  end

  # POST /user_books or /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to @user_book, notice: "User book was successfully created." }
        format.json { render :show, status: :created, location: @user_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1 or /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to @user_book, notice: "User book was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1 or /user_books/1.json
  def destroy
    @user_book.destroy!

    respond_to do |format|
      format.html { redirect_to user_books_path, notice: "User book was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_book_params
      params.require(:user_book).permit(:user_id, :book_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
    <% if book.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :author %><br>
      <%= form.text_field :author %>
    </div>
  
    <div>
      <%= form.label :price %><br>
      <%= form.number_field :price %>
    </div>
  
    <div>
      <%= form.label :published_date %><br>
      <%= form.date_select :published_date %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

<br>

<%= link_to "Back to Home Books Page", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Published Date</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= number_to_currency(book.price) %></td>
        <td><%= book.published_date %></td>
        <td><%= link_to "Show", book %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "New Book", new_book_path %> |
<%= link_to "User Books Index", user_books_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with(model: @book) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :published_date %><br>
    <%= form.date_field :published_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "Back to Home Books Page", books_path %>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @book.title %></h1>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Published Date:</strong>
  <%= @book.published_date %>
</p>

<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back to Home Books Page", books_path %>

app/views/dashboards/show.html.erb
<h1>You're logged in! Welcome!</h1>
<%= link_to "Sign Out", destroy_admin_session_path %>

app/views/home/index.html.erb
<h1>Hello Heroku Staging</h1>
<p>This is running in production!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection34FaqiangMei</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      .flash { padding: 10px; margin: 10px 0; border-radius: 5px; }
      .flash.notice { background-color: #d4edda; color: #155724; }   /* green */
      .flash.alert  { background-color: #f8d7da; color: #721c24; }   /* red */
      .flash.error  { background-color: #f8d7da; color: #721c24; }   /* red */
      .flash.success { background-color: #d1ecf1; color: #0c5460; } /* blue */
    </style>
  </head>

  <body>
    <header>
      <% if admin_signed_in? %>
        <p>Logged in as <%= current_admin.email %></p>
        <%= button_to "Logout",
                      destroy_admin_session_path,
                      method: :delete,
                      data: { turbo: "false" },
                      class: "btn btn-secondary" %>
      <% else %>
        <%= button_to "Sign in with Google",
                      admin_google_oauth2_omniauth_authorize_path,
                      method: :post,
                      data: { turbo: "false" },
                      class: "btn btn-danger" %>
      <% end %>
      <hr>
    </header>


    <% flash.each do |key, message| %>
      <div class="flash <%= key %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/user_books/_form.html.erb
<%= form_with(model: user_book) do |form| %>
  <% if user_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>
      <ul>
        <% user_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, "User", style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, :username, include_blank: "Select a user" %>
  </div>

  <div>
    <%= form.label :book_id, "Book", style: "display: block" %>
    <%= form.collection_select :book_id, Book.all, :id, :title, include_blank: "Select a book" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_books/_user_book.html.erb
<div id="<%= dom_id user_book %>">
  <p>
    <strong>User:</strong>
    <%= user_book.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= user_book.book_id %>
  </p>

</div>

app/views/user_books/edit.html.erb
<h1>Editing user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Show this user book", @user_book %> |
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/index.html.erb
<h1>User Books</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Title</th>
    </tr>
  </thead>
  <tbody>
    <% @user_books.each do |user_book| %>
      <tr>
        <td><%= user_book.user.username %></td>
        <td><%= user_book.book.title %></td>
        <td><%= link_to "Show", user_book %></td>
        <td><%= link_to "Edit", edit_user_book_path(user_book) %></td>
        <td><%= link_to "Destroy", user_book, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "New User Book", new_user_book_path %> |
<%= link_to "Books Index", books_path %> |
<%= link_to "Users Index", users_path %>

app/views/user_books/new.html.erb
<h1>New user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_book %>

<div>
  <%= link_to "Edit this user book", edit_user_book_path(@user_book) %> |
  <%= link_to "Back to user books", user_books_path %>

  <%= button_to "Destroy this user book", @user_book, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Edit User Book</h1>

<%= render "form", user_book: @user_book %>

<br>

<%= link_to "Back", user_books_path %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Back to User Books", user_books_path %>

app/views/users/new.html.erb
<h1>New User Book</h1>

<%= render "form", user_book: @user_book %>

<br>

<%= link_to "Back", user_books_path %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>
<br>
<%= link_to "Back to Books", books_path %>